# Generated by Django 5.1.1 on 2024-10-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
