# Generated by Django 5.1.1 on 2024-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='denomination',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currencyinventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
